### ISSUE TITLE
Bloquear ou não bloquear? Eis a questão!

### ISSUE THREAD

**Issue by luizcasali** [grupozap/guild-paranoias#7]
- INCIDENTE A SER TRATADO
Após a implementação do novo FIREWALL no grupo, começamos a ter incidentes relacionados a bloqueio de conteúdo.

- COMO É FEITO O BLOQUEIO
O Fortigate usa sua central para categorizar sites e alimentar os dispositivos com essa base de dados. Depois ativamos o serviço para bloquear ou não sites nessas categorias.
ex de categorias: 
-- CHILD ABUSE
-- EXTREMIST GROUPS
-- DDNS
-- ABORTION
-- GLAMBLING
-- WEAPONS (SALES)
-- ETC...

- COMO FOI IMPLEMENTADO
Deixamos somente subcategorias de SECURITY RISK e LIABILITY com bloqueios, porém alguns serviços dessas categorias, como por exemplo, DDNS (security risk) são serviços utilizados.

- QUAL A PERGUNTA A SER RESPONDIDA
Devemos liberar tudo e remover essa feature de segurança ou continuar usando o serviço de filtragem e ir liberando conforme for preciso?

**Comment by luizcasali** [comment]
explicando melhor o bloqueio.

temos categorias e sub categorias.
cada item pode ter 
- BLOCK
- ALLOW
- MONITOR

podemos também bloquear uma categoria e liberar um domínio específico dentro daquela item que está bloqueado.

Os padrões são baseados no RATING SYSTEM americano que governa conteúdos em diversos tipos de mídia, como jogos, filmes, e outros itens no país.

temos os níveis pré estabelecidos
- G
- PG-13
- R

Estávamos usando o R que é o mais permissivo e liberando itens necessários criando assim um grupo CUSTOM.

**Comment by Lucas-L-Alcantara** [comment]
Quando conversamos sobre isso internamente, pensamos em manter apenas os bloqueios de categorias para assuntos que são abordados por leis e de recursos que nos tragam alto risco. De resto, confiar no bom senso da galera. Exemplos de bloqueios: TOR, Pornografia, P2P...

**Comment by luizcasali** [comment]
Verifiquei todos os itens, e selecionei os abaixo para decidirmos se vamos bloquear ou nao.
Os outros julguei não haver necessidade para bloqueio e não precisariam entrar na conversa.


POTENTIALLY LIABLE
child abuse
discrimination
drug abuse
explicit violence
extremist groups
hacking
illegal or unethical
plagiarism
proxy avoidance

ADULT/MATURE CONTENT
abortion
pornography
weapons (sales)

SECURITY RISKS
dynamic dns
malicious websites
newly observed domain
newly registered domain
phishing
spam urls

**Comment by luizcasali** [comment]
eu votaria por deixar liberado:
DYNAMIC DNS
NEWLY OBSERVED DOMAIN
NEWLY REGISTERED DOMAIN
HACKING (pode ser usado para estudo)
ILLEGAL OR UNETHICAL (pode ser usado para educação pessoal)
PLAGIARISM 

obs: algumas categorias como illegal or unethical, plagiarism ou hacking são meio obscuras e não sabemos exatamente o que irá bloquear.

**Comment by Lucas-L-Alcantara** [comment]
Eu deixaria só esses:

POTENTIALLY LIABLE
child abuse
discrimination

ADULT/MATURE CONTENT
pornography

SECURITY RISKS
malicious websites
newly observed domain
newly registered domain
phishing
spam urls

... ainda sssim acho que é a policy POTENTIALLY LIABLE , se não me engano, que bloqueia as vezes sites de notícias

Além da rede TOR e P2P
:smile:

**Comment by luizcasali** [comment]
os seguintes itens serão bloqueados

POTENTIALLY LIABLE
child abuse
discrimination

ADULT/MATURE CONTENT
pornography

SECURITY RISKS
malicious websites
phishing
spam urls
